### ISSUE TITLE
Migration "...Failed!"

### ISSUE THREAD

**Issue by theopen-institute** [moodlehq/moodle-tool_migratehvp2h5p#1]
When running the command line tool, I get the following output:

```
Migrating ID:82	#2.5 - The ethics and outcomes of research	 course:8	Course Name
3-2-the-ethics-and-outcomes-of-research-82.h5p
	 ...Failed!
```

and the web-based tool simply says "Error migration hvp ctivity with id 82".

I've tested with numerous different h5p files, but the results are always similar. Is there any way to know what the error here is?

**Comment by ferranrecio** [comment]
Hi,

Thanks for reporting this issue. We are working on improving the debug information and we expect to have it done in the next weeks. Meanwhile, we recommend updating both mod_hvp and tool_migratehvp2h5p to the latest versions. We detect some problems migrating using old mod_hvp versions and now tool_migratehvp2h5p has a minimum hvp version requirement.

Sorry for the inconvenience,

Ferran.

**Comment by merrill-oakland** [comment]
With the latest from master, I am getting the failed message, but the additional detail:
`Exception: Competencies are not enabled.`
Of course I don't know if that is the same problem @theopen-institute is seeing.

**Comment by sarjona** [comment]
Hi @theopen-institute !
Thanks for reporting this issue! It seems that it was fixed (thanks Eric!!), so I would suggest upgrading to the latest version.
If you keep facing similar problems, open a new issue, sharing as many information as you can in order to be able to reproduce it locally ;-)
