### ISSUE TITLE
Event is triggered off on wrong context

### ISSUE THREAD

**Issue by merrill-oakland** [moodlehq/moodle-tool_migratehvp2h5p#3]
When we migrate, we are getting this error:
```
	Exception: Can't find data record in database table context. (SELECT * FROM {context} WHERE id = ?
[array (
  0 => '3358078',
)])
```
I dug into it, and it is actually trying to get a context by id using the course modules id number for triggering the event. Which means that it is actually pulling the wrong context. Now if you are on a site without lots of deletes, you might never notice this. This is because there should always be more rows in mdl_context than mdl_course_modules. So only if the context with an ID matching the CM id was deleted would you see it. But even if you don't get the fatal error, the wrong context will be logged against.

The bits of code are:
classes/api.php::trigger_migration_event():
```
$record->contextid = $hvpcm->id;
```
and classes/event/hvp_migrated.php::create_from_record():
```
'context' => \context::instance_by_id($record->contextid),
```
You can see the record->contextid is being set to the CM id instead.

**Comment by ferranrecio** [comment]
Thanks a lot. Your commit is been integrated.
