### ISSUE TITLE
Database error for activities with maxgrade of 0

### ISSUE THREAD

**Issue by haietza** [moodlehq/moodle-tool_migratehvp2h5p#35]
Migration fails with the following error for activities that have a maximum grade of 0:

Exception: Coding error detected, it must be fixed by a programmer: moodle_database::update_record_raw() id field must be specified.

It appears to be an issue with a grade_item being created for the new h5pactivity.

**Comment by sarjona** [comment]
It seems you're not using the latest version of the migration tool because it was reported previously and fixed in the latest version. For more information, you can look at https://github.com/moodlehq/moodle-tool_migratehvp2h5p/issues/7
