### ISSUE TITLE
Use the mod_hvp author when migrating into content bank too

### ISSUE THREAD

**Issue by sarjona** [moodlehq/moodle-tool_migratehvp2h5p#36]
During an H5P session with RAMU (Spanish universities association), they have raised an issue they have faced when migrating content from mod_hvp to mod_h5pactivity: the author of the content in the content bank is always the user running the upgrade process.
In order to let teachers edit these contents later in the content bank, it would be nice migrating the author of the mod_hvp too.

**Comment by Tottebee** [comment]
Hi Sarjona,
unfortunately we delete our logs after 30 days..... Can you tell me where in the database I can find the authorid of the h5p content, to alter it? In the mdl_file record, the authorid is also written but not used for the restrictions. 
Another possibilty to solve the problem could be to use the trainerid from the course where the hvp content is used.
The problem with the author also occurs when making a course backup and import it to another moodle instance.
help would be great. 
regards 
Thorsten

**Comment by doctorlard** [comment]
Hi @sarjona - I've opened PR #42 as part of Catalyst work for @Tottebee on this issue; this patch adds a `get_hvp_author` function which will:

1. attempt to determine a user id from the log - your commit from #37
2. failing that, attempt to determine a user id from an asset, if one exists, in `mdl_files` and who also has `moodle/contentbank:manageanycontent` permission in the course (editing teacher);
3. failing that, set the user id to the first course user with `moodle/contentbank:manageanycontent` (editing teacher),
4. failing that, fall back to the user id that is running the import (the current behaviour).

The patch also contains unit tests for the function covering the above scenarios; please note they have been written in the absence of any `mod_hvp` test code or generators... unfortunately "create a test suite for mod_hvp" was not on the list of things to do and thus very much out of scope!
