### ISSUE TITLE
Moodle 3.11 / 4.0 support

### ISSUE THREAD

**Issue by giliomeejg** [moodlehq/moodle-tool_migratehvp2h5p#45]
Are there any plans to add Moodle 3.11 / 4.0 support for this plugin?

**Comment by Urpokarhu1** [comment]
Any support for Moodle 4.1?

**Comment by sarjona** [comment]
Hi @Urpokarhu1!
The current version of the plugin supports Moodle 4.1: https://moodle.org/plugins/tool_migratehvp2h5p/versions ;-)
