### ISSUE TITLE
Submission content with null raw_score causes error

### ISSUE THREAD

**Issue by merrill-oakland** [moodlehq/moodle-tool_migratehvp2h5p#8]
If you have an hvp submission with a null raw_score (which it allows), you see this error during migration:

```
Migrating ID:4	Something	 course:2	Test course: S
something-4.h5p
	Exception: Error writing to database (ERROR:  null value in column "rawscore" violates not-null constraint
DETAIL:  Failing row contains (2, 2, null, 1597357737, compound, , , , {"extensions":{"https:\/\/h5p.org\/x-api\/h5p-machine-name":"H5P..., null, null, 0, 1, 0).
INSERT INTO mdl_h5pactivity_attempts_results (attemptid,subcontent,timecreated,interactiontype,description,correctpattern,response,additionals,rawscore,maxscore,duration,completion,success) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13) RETURNING id
[array (
  'attemptid' => 2,
  'subcontent' => NULL,
  'timecreated' => 1597357737,
  'interactiontype' => 'compound',
  'description' => '',
  'correctpattern' => '',
  'response' => '',
  'additionals' => '{"extensions":{"https:\\/\\/h5p.org\\/x-api\\/h5p-machine-name":"H5P.DocumentationTool"},"contextExtensions":{}}',
  'rawscore' => NULL,
  'maxscore' => NULL,
  'duration' => 0,
  'completion' => 1,
  'success' => 0,
)])
```

I can reproduce this with the Documentation Tool library. If you set it up in hvp, with a Export page, you will have an option to submit it. That submission will then cause a problem during conversion.

Interestingly, if you use doc tool in h5p, the setup pages still have you enter things like naming the submit button, but the button won't be there when you actually try it out.

**Comment by austin-powell** [comment]
We are seeing the same behavior when trying to migrate any of our Essay type HVP activities

`Error migration hvp activity with id 2: Error writing to database (Column 'rawscore' cannot be null INSERT INTO mdl_h5pactivity_attempts_results (attemptid,subcontent,timecreated,interactiontype,description,correctpattern,response,additionals,rawscore,maxscore,duration,completion,success) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?) [array ( 0 => 741, 1 => NULL, 2 => 1600958347, 3 => 'long-fill-in', 4 => '
Your mail carrier delivers the mail three days a week and chooses which days the mail is delivered to your residence. What might happen?', 5 => '', 6 => '', 7 => '{"extensions":{"http:\\/\\/h5p.org\\/x-api\\/h5p-local-content-id":2},"contextExtensions":{}}', 8 => NULL, 9 => NULL, 10 => 0, 11 => 1, 12 => 0, )])`

**Comment by sarjona** [comment]
Although with the patch the error is fixed and the H5P activities with null maxscore or rawcore are migrated, the information for the "Documentation tool" won't be displayed as expected until the following issue gets fixed in mod_h5pactivity: https://tracker.moodle.org/browse/MDL-69895
